/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.me.clinical;

/**
 *
 * @author Asim Rana
 */
import java.sql.Connection;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class Processed extends javax.swing.JFrame {

    /**
     * Creates new form Processed
     */
    public Processed() {
        initComponents();
    }
    public Processed(String id , String aname) {
       
        initComponents();
        dname = aname;
         pid = Integer.parseInt(id);
        showValues();
    }
    public void showValues()
    {
        try{
                Class.forName("org.sqlite.JDBC");
		Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\eclipse\\test.db");
		Statement stmt = conn.createStatement();
                
                
                ResultSet rset = stmt.executeQuery("SELECT name , contact  FROM Patient where id = " + pid + " and doctor = '" + dname + "';");
                
                if(rset.next())
                {
                    
                    String name = rset.getString("name");
                   
                    contact = rset.getString("contact");
                   
                    PRName.setText(name);
                    
                    Prid.setText(Integer.toString(pid));
                    
                    CrNo.setText(contact);
                    
                    conn.close();
                    stmt.close();
                    
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null , "No record found");
                    conn.close();
                    stmt.close();
                    this.dispose();
                    new DProfile().setVisible(true);
                    
                    
                }
               
                 
            }
            catch(Throwable e)
            {
                System.out.println(e.getMessage());
            }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PName = new javax.swing.JLabel();
        Pid = new javax.swing.JLabel();
        Prid = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        CrNo = new javax.swing.JLabel();
        DLabel = new javax.swing.JLabel();
        DField = new javax.swing.JTextField();
        Complete = new javax.swing.JButton();
        History = new javax.swing.JButton();
        PRName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(290, 150, 0, 0));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/clinical/newpackage/edited.png"))); // NOI18N

        PName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PName.setForeground(new java.awt.Color(255, 255, 255));
        PName.setText("Patient Name:");

        Pid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Pid.setForeground(new java.awt.Color(255, 255, 255));
        Pid.setText("Patient Id:");

        Prid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Prid.setForeground(new java.awt.Color(255, 255, 255));

        Contact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("Contact.No:");

        CrNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CrNo.setForeground(new java.awt.Color(255, 255, 255));

        DLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DLabel.setForeground(new java.awt.Color(255, 255, 255));
        DLabel.setText("Disease:");

        Complete.setText("Complete");
        Complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteActionPerformed(evt);
            }
        });

        History.setText("History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });

        PRName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PRName.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(Complete)
                        .addGap(18, 18, 18)
                        .addComponent(History))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DLabel)
                            .addComponent(Pid)
                            .addComponent(Contact)
                            .addComponent(PName))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Prid)
                            .addComponent(CrNo)
                            .addComponent(DField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PName)
                    .addComponent(PRName))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pid)
                    .addComponent(Prid))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contact)
                    .addComponent(CrNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DLabel)
                    .addComponent(DField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Complete)
                    .addComponent(History))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/clinical/newpackage/editback.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteActionPerformed

        try{
                Class.forName("org.sqlite.JDBC");
		Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\eclipse\\test.db");
		Statement stmt = conn.createStatement();
                
                String s = DField.getText();
                DateFormat dateFormat = new SimpleDateFormat("dd-MM-YYYY");
                Date d = new Date();
                String yourDate = dateFormat.format(d);
                
                stmt.executeUpdate("Update Patient SET disease = '" + s + "',lastvisit = '" + yourDate + "' where id = " + pid + ";");
                stmt.executeUpdate("Update Appointment SET status = 'Yes' where contact = '" + contact + "';");
                JOptionPane.showMessageDialog(null , "Patient record has been successfully updated");
                
               
                 conn.close();
                 stmt.close();
            }
            catch(Throwable e)
            {
                System.out.println(e.getMessage());
            }
        
        this.dispose();
        new DProfile().setVisible(true);
    }//GEN-LAST:event_CompleteActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        
        try{
                Class.forName("org.sqlite.JDBC");
		Connection conn = DriverManager.getConnection("jdbc:sqlite:C:\\eclipse\\test.db");
		Statement stmt = conn.createStatement();
                
                
                ResultSet rset = stmt.executeQuery("Select disease , lastvisit from Patient where id = " + pid + ";");
                if(rset.next())
                {
                    String d = rset.getString("disease");
                    String last = rset.getString("lastvisit");
                    JOptionPane.showMessageDialog(null , "Date:         " + last + "\nDisease         " + d); 
                }
                else
                {
                    JOptionPane.showMessageDialog(null , "No history found"); 
                }
                
               
                 conn.close();
                 stmt.close();
            }
            catch(Throwable e)
            {
                System.out.println(e.getMessage());
            }
       
    }//GEN-LAST:event_HistoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            this.dispose();
            new DProfile().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Processed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Processed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Processed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Processed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Processed().setVisible(true);
            }
        });
    }
    int pid;
    
    String contact;
    String dname;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Complete;
    private javax.swing.JLabel Contact;
    private javax.swing.JLabel CrNo;
    private javax.swing.JTextField DField;
    private javax.swing.JLabel DLabel;
    private javax.swing.JButton History;
    private javax.swing.JLabel PName;
    private javax.swing.JLabel PRName;
    private javax.swing.JLabel Pid;
    private javax.swing.JLabel Prid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
